### ISSUE TITLE
In latest version v1.07 switched fan speeds and temperatures

### ISSUE THREAD

**Issue by zoomtronicOR** [JamesSmith2/EthMonitoring#10]
Hi, I notice that my fan speeds are to low, and i look closely, just to find out that temperature and fan speed readings are switched.

**Comment by JamesSmith2** [comment]
Can you comment what software are you monitoring with it?

**Comment by zoomtronicOR** [comment]
I am using same as before, no additional software, just v 1.07 , before that were previous version. And on rig itself ethMonitoring shows correct values, but on web page https://ethmonitoring.com/site/miners
shows switched values. 
![2019-05-05_14-33-54](https://user-images.githubusercontent.com/27694912/57194123-46090900-6f43-11e9-9ee1-906c3122e343.png)
![2019-05-05_14-36-12](https://user-images.githubusercontent.com/27694912/57194125-4903f980-6f43-11e9-86a5-138e8bfc6cc7.png)

**Comment by JamesSmith2** [comment]
Can you tell me claymore version?

**Comment by zoomtronicOR** [comment]
v11.8

**Comment by JamesSmith2** [comment]
can you switch host to "localhost"

**Comment by zoomtronicOR** [comment]
I just did, and still the same

**Comment by JamesSmith2** [comment]
Can you run this ethmonitoring.exe and after 60s upload log.txt file.

[EthMonitoringv1.07.zip](https://github.com/JamesSmith2/EthMonitoring/files/3145530/EthMonitoringv1.07.zip)

**Comment by zoomtronicOR** [comment]
Here is log from v1.07
[log.txt](https://github.com/JamesSmith2/EthMonitoring/files/3145536/log.txt)

**Comment by JamesSmith2** [comment]
can you join discord: https://discord.gg/yHATfbA ?

**Comment by zoomtronicOR** [comment]
No time for now, I am working, here is more details with previous version it works fine
![2019-05-05_15-11-07](https://user-images.githubusercontent.com/27694912/57194526-393ae400-6f48-11e9-85f7-f1fd4c10a78d.png)
![2019-05-05_15-11-23](https://user-images.githubusercontent.com/27694912/57194527-3dff9800-6f48-11e9-88b8-db8e4554955c.png)

**Comment by zoomtronicOR** [comment]
I will leave version 1.03 for now i guess You'll locate problem

**Comment by JamesSmith2** [comment]
Can you try this one.

[EthMonitoringv1.08.zip](https://github.com/JamesSmith2/EthMonitoring/files/3145556/EthMonitoringv1.08.zip)

**Comment by zoomtronicOR** [comment]
works fine with new version 1.08

**Comment by JamesSmith2** [comment]
great

**Comment by zoomtronicOR** [comment]
Thanks
