### ISSUE TITLE
EthMonitoring doesn't open with .NetFramework 4.8

### ISSUE THREAD

**Issue by darkside61** [JamesSmith2/EthMonitoring#11]
Having Windows 10 with .NetFramework 4.8 installed, EthMonitoring doesn't start...
Any help on this?

Thanks
darkside61

**Comment by JamesSmith2** [comment]
Hi,

Try this: https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by darkside61** [comment]
Hello JamesSmith2.
Having the .Net4.8 installed Windows does not allow to instal .Net4.61.
How do I uninstall .Net4.8?

Thank you for your fast answer!
By the way, good job!

darkside61

**Comment by JamesSmith2** [comment]
Hey,

Try this one, it's compiled with net 4.8
[EthMonitoringv1.10_net48.zip](https://github.com/JamesSmith2/EthMonitoring/files/3655801/EthMonitoringv1.10_net48.zip)

**Comment by darkside61** [comment]
Hey.
Thank you for trying to help.
Same behaviour: it starts, but whem I put my mouse over the icon in the program tray to open the program, the icon disapears.

Any hint?

darkside61

**Comment by JamesSmith2** [comment]
Hello,

Is there debug.txt or log.txt generated?

**Comment by darkside61** [comment]
Hey.
Thank you for trying to help.
Same behaviour: it starts, but whem I put my mouse over the icon in the program tray to open the program, the icon disapears.

Here it is.

darkside61



[Log Ethmonitoring.txt](https://github.com/JamesSmith2/EthMonitoring/files/3662376/Log.Ethmonitoring.txt)

**Comment by JamesSmith2** [comment]
Hey,

try removing settings. json

**Comment by darkside61** [comment]
Excellent ! It worked!
Great job!

Thank you so much.

darkside61
