### ISSUE TITLE
No 'Start Monitoring' button

### ISSUE THREAD

**Issue by delmarz** [JamesSmith2/EthMonitoring#2]
I'm using windows 10, but it seems the button of 'Start Monitoring' are not visible as you can see in the screenshot. 

![saas](https://user-images.githubusercontent.com/7381514/30725159-717d4600-9ef7-11e7-9c08-f57cc7da5024.PNG)

**Comment by JamesSmith2** [comment]
Hey,

It will start automatically when added.
