### ISSUE TITLE
Can't monitor dtsm miner. 

### ISSUE THREAD

**Issue by sifotes** [JamesSmith2/EthMonitoring#3]
I have tried localhost:port , myip:port and myportforwardedDomain:port , nothing connects to dtsm.
All options work from a browser. 
Any suggestions?

**Comment by JamesSmith2** [comment]
Hi,

Didn't receive notification from github, did you add telemetry for dstm?

**Comment by sifotes** [comment]
Yes telemetry was configured. As I said the expected information is viewable from a browser, but not EthMonitoring.

**Comment by JamesSmith2** [comment]
Do you use custom port or default 2222?

**Comment by sifotes** [comment]
A custom port. My setup works everywhere else, I've moved past this app since it doesn't work for dtsm. Just thought I'd report the issue. If there's any details I haven't provided already let me know.

**Comment by JamesSmith2** [comment]
Hi,

That's the issue there, current version supports default port, next version i have already coded custom port support for ZM, you can give it a try when released. Hopefully this week.
