### ISSUE TITLE
Doesn't work with  ethminer 0.14.0.dev4

### ISSUE THREAD

**Issue by yunuza** [JamesSmith2/EthMonitoring#5]
Doesn't work with ethminer  0.14.0.dev4 on Windows 10 x64 (host: localhost).
Statsonly is working. Claymore was working before too.

**Comment by invidtiv** [comment]
windows version : It does I am using it with ethminer 0.14.0dev4 
are you using --api-port xxxx on the commandline?

The linux version doesn t work with ethminer... because the ethminer doesn t close the connection after sending the json response.

**Comment by yunuza** [comment]
Thanks, that worked.
