### ISSUE TITLE
Excavator issue

### ISSUE THREAD

**Issue by Felvy** [JamesSmith2/EthMonitoring#6]
Since the latest update to Nicehash I'm not able to use EthMonitoring. Port is correct (have it set to 5100) and it worked prior to the update.

**Comment by JamesSmith2** [comment]
Hey,

Can you try this: https://www.upload.ee/files/8318003/EthMonitoring_v32.zip.html

**Comment by Felvy** [comment]
Still not working. Just says Offline. Restarted Nicehash/Excavator and all that. Confirmed its listening on 5100.

**Comment by JamesSmith2** [comment]
Hey, did you try latest uploaded version? what is excavator version?

**Comment by Felvy** [comment]
All good :). The most recent version you released works well.
