### ISSUE TITLE
source code is not right version

### ISSUE THREAD

**Issue by nvmax** [JamesSmith2/EthMonitoring#7]
Any Chance you could actually update the source code to the correct revision? the source code is v0.0.21 when it shows it supposed to be v0.0.34.

**Comment by JamesSmith2** [comment]
Hi,

I can't update, because of competition has stolen so many, if you want to discuss about it, join discord and we can talk.

**Comment by nvmax** [comment]
Understandable not really interested in full source code just the portion of how you get details from phoenix miners jsonrpc, can you share your method, it has stumped me.

**Comment by nvmax** [comment]
oh yeah even tried in vb.net console app, same issue 

`Dim receiveBytes = New Byte(255) {}
        Using socket = New Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)
            socket.Connect("192.168.1.143", 8801)
            socket.Send(Encoding.ASCII.GetBytes("{""id"":0,""jsonrpc"":""2.0"",""method"":""miner_getstat1""}\n "))
            socket.Receive(receiveBytes, receiveBytes.Length, SocketFlags.None)
            socket.Close()
        End Using

        Dim responseJson = Encoding.ASCII.GetString(receiveBytes)
        _splitString = responseJson
        Console.WriteLine(responseJson)`

**Comment by JamesSmith2** [comment]
what's that space at the end?

**Comment by nvmax** [comment]
a mistype lol, though still doesnt change the outcome, works fine for claymore, not for phoenix driving me nuts as hell...

**Comment by JamesSmith2** [comment]
`var clientSocket = new System.Net.Sockets.TcpClient();
                

                if (clientSocket.ConnectAsync(_host, _port).Wait(5000))
                {
                    string get_menu_request = "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"miner_getstat1\",\"psw\":\"" + _password + "\"}\n";
                    NetworkStream serverStream = clientSocket.GetStream();
                    byte[] outStream = System.Text.Encoding.ASCII.GetBytes(get_menu_request);
                    serverStream.Write(outStream, 0, outStream.Length);
                    serverStream.Flush();

                    byte[] inStream = new byte[clientSocket.ReceiveBufferSize];
                    serverStream.Read(inStream, 0, (int)clientSocket.ReceiveBufferSize);
                    string _returndata = System.Text.Encoding.ASCII.GetString(inStream);

                    if (_returndata.Length == 0)
                        throw new Exception("Invalid data");`

**Comment by nvmax** [comment]
Seriously thats all I needed ? WTF!  just a simple freaking  & vblf

**Comment by JamesSmith2** [comment]
https://media3.giphy.com/media/L4AQvif7x9fS8/giphy.gif

**Comment by nvmax** [comment]
exactly man exactly, I seriously was trying to figure that out for 2 days lol..  as soon as that worked I stood up and was like REALLY WTF REALLY! you gotta be kidding me... lol.

**Comment by JamesSmith2** [comment]
Well great, now it works. :)

**Comment by nvmax** [comment]
yeah thanks man! really I dont think I would of figured that out with out your help, I was seriously stumped, I making a program that monitors a few miner softwares, and interacts with wemo and belkin wifi power adapters to switch them off when it has detected a failure or no response. waits specified time and turns them back on.
