### ISSUE TITLE
GPU display bug in 14 GPU mining rig

### ISSUE THREAD

**Issue by noxouille** [JamesSmith2/EthMonitoring#9]
Hello, 

with release v1.02, the bug seems to appear in both Android app and web interface.
[Android app](https://drive.google.com/open?id=1z476akTUTtGUwkeb6AaiEAGWlZ48FCqg)
[Web interface](https://drive.google.com/open?id=1RNU8GVxN6vl-C3UXvoYdr65sf96xaxSL)
[Compact view](https://drive.google.com/open?id=1gXMKk1O2PtnnMo0jSpCL1U1NRQicpVFM)

Any chance this will get fixed?

**Comment by noxouille** [comment]
Hi sorry about that. I re-uploaded the images here 
https://imgur.com/a/lGT9tvT

**Comment by JamesSmith2** [comment]
What software are you using for mining?

**Comment by noxouille** [comment]
Claymore V11.7

**Comment by JamesSmith2** [comment]
Do you have integrated GPU enabled also?

**Comment by noxouille** [comment]
I am using [Sapphire INCA CS-14 ](http://www.sapphiretech.com/productdetial.asp?pid=EFCE8CC8-7A7B-4A58-BA86-028A7CD56846&lang=eng), which I believe there is no integrated GPU, only 14 dedicated GPU for mining.

**Comment by JamesSmith2** [comment]
[EthMonitoringv1.03_debug.zip](https://github.com/JamesSmith2/EthMonitoring/files/2517873/EthMonitoringv1.03_debug.zip)
Can you run this and send me log.txt, i'l get json from claymore to see what's causing it.

**Comment by noxouille** [comment]
[log.txt](https://github.com/JamesSmith2/EthMonitoring/files/2517912/log.txt)
